import { Language, UserProfile } from './types';

// --- RAG Knowledge Base (Simulated Local Vector DB) ---
export const AGRICULTURAL_KNOWLEDGE_BASE = [
  {
    keywords: ['fall armyworm', 'maize', 'corn', 'worm'],
    content: "Fall Armyworm (Spodoptera frugiperda) is a major pest in Maize. Early detection shows window-pane damage on leaves. Control: Metarhizium anisopliae (bio) or Emamectin benzoate (chemical)."
  },
  {
    keywords: ['blight', 'potato', 'tomato', 'black spots'],
    content: "Late Blight (Phytophthora infestans) causes black lesions on leaves. It spreads rapidly in humid weather. Control: Mancozeb (preventive) or Metalaxyl (curative)."
  },
  {
    keywords: ['soil', 'ph', 'acidic'],
    content: "Acidic soil (pH < 6.0) limits nutrient uptake. Amend with Lime (Calcium Carbonate). Optimal pH for most crops is 6.5-7.5."
  },
  {
    keywords: ['nitrogen', 'yellow leaves'],
    content: "Nitrogen deficiency causes yellowing of older leaves (V-shaped). Apply Urea or Compost."
  }
];

// --- Translations ---
export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    welcome: "Welcome",
    tagline: "Your AI Agronomist Companion",
    login: "Login to Dashboard",
    dashboard: "Farm Dashboard",
    scanner: "Crop Doctor",
    field: "Field Architect",
    soil: "Soil Health Lab",
    coach: "AI Coach",
    community: "Community Forum",
    weather: "Weather",
    moisture: "Soil Moisture",
    alerts: "Active Alerts",
    scan_btn: "Start Scan",
    analyzing: "Analyzing...",
    confidence: "Confidence",
    severity: "Severity",
    treatment: "Recommended Treatment",
    logout: "Logout",
    market: "Market Prices",
    tasks: "Upcoming Tasks",
    gen_report: "Generate Deep Research Report",
    enter_data: "Enter Lab Data",
    organic: "Organic",
    chemical: "Chemical",
    disease_detected: "Disease Detected",
    healthy: "Crop looks healthy",
    greeting_morning: "Good Morning",
    greeting_afternoon: "Good Afternoon",
    greeting_evening: "Good Evening",
    tutorial_intro: "I am AgriGuard, your AI assistant. Use the Dashboard to monitor your farm, Field Architect to map boundaries, and Crop Doctor to diagnose diseases.",
    magic_wand: "Magic Wand (Auto-Detect)",
  },
  [Language.HINDI]: {
    welcome: "स्वागत है",
    tagline: "आपका एआई कृषि साथी",
    login: "डैशबोर्ड में लॉग इन करें",
    dashboard: "खेत डैशबोर्ड",
    scanner: "फसल डॉक्टर",
    field: "खेत वास्तुकार",
    soil: "मिट्टी स्वास्थ्य प्रयोगशाला",
    coach: "एआई कोच",
    community: "समुदाय मंच",
    weather: "मौसम",
    moisture: "मिट्टी की नमी",
    alerts: "सक्रिय अलर्ट",
    scan_btn: "स्कैन शुरू करें",
    analyzing: "विश्लेषण कर रहा है...",
    confidence: "आत्मविश्वास",
    severity: "गंभीरता",
    treatment: "अनुशंसित उपचार",
    logout: "लॉग आउट",
    market: "बाजार भाव",
    tasks: "आगामी कार्य",
    gen_report: "विस्तृत रिपोर्ट बनाएं",
    enter_data: "डेटा दर्ज करें",
    organic: "जैविक",
    chemical: "रासायनिक",
    disease_detected: "रोग का पता चला",
    healthy: "फसल स्वस्थ लग रही है",
    greeting_morning: "सुप्रभात",
    greeting_afternoon: "शुभ दोपहर",
    greeting_evening: "शुभ संध्या",
    tutorial_intro: "मैं एग्रीगार्ड हूं, आपका एआई सहायक। अपने खेत की निगरानी के लिए डैशबोर्ड, सीमाओं को मैप करने के लिए फील्ड आर्किटेक्ट, और बीमारियों का निदान करने के लिए क्रॉप डॉक्टर का उपयोग करें।",
    magic_wand: "जादुई छड़ी (ऑटो-डिटेक्ट)",
  },
  [Language.BENGALI]: {
    welcome: "স্বাগতম",
    tagline: "আপনার এআই কৃষি বন্ধু",
    login: "লগইন করুন",
    dashboard: "ফার্ম ড্যাশবোর্ড",
    scanner: "ফসল ডাক্তার",
    field: "ফিল্ড আর্কিটেক্ট",
    soil: "মাটি স্বাস্থ্য ল্যাব",
    coach: "এআই কোচ",
    community: "কমিউনিটি",
    weather: "আবহাওয়া",
    moisture: "মাটির আর্দ্রতা",
    alerts: "সতর্কতা",
    scan_btn: "স্ক্যান শুরু",
    analyzing: "বিশ্লেষণ...",
    confidence: "বিশ্বাস",
    severity: "তীব্রতা",
    treatment: "চিকিৎসা",
    logout: "লগ আউট",
    market: "বাজার দর",
    tasks: "আসন্ন কাজ",
    gen_report: "বিস্তারিত রিপোর্ট তৈরি করুন",
    enter_data: "ল্যাব ডেটা দিন",
    organic: "জৈব",
    chemical: "রাসায়নিক",
    disease_detected: "রোগ শনাক্ত হয়েছে",
    healthy: "ফসল সুস্থ দেখাচ্ছে",
    greeting_morning: "শুভ সকাল",
    greeting_afternoon: "শুভ বিকেল",
    greeting_evening: "শুভ সন্ধ্যা",
    tutorial_intro: "আমি এগ্রিগগার্ড, আপনার এআই সহকারী। ফার্ম ড্যাশবোর্ড ব্যবহার করুন খামার পর্যবেক্ষণের জন্য।",
    magic_wand: "ম্যাজিক ওয়ান্ড",
  },
  [Language.TAMIL]: {
    welcome: "வரவேற்கிறோம்",
    tagline: "உங்கள் AI விவசாயத் தோழன்",
    login: "உள்நுழையவும்",
    dashboard: "பண்ணை குழு",
    scanner: "பயிர் மருத்துவர்",
    field: "கள வடிவமைப்பாளர்",
    soil: "மண் ஆய்வகம்",
    coach: "AI பயிற்சியாளர்",
    community: "சமூகம்",
    weather: "வானிலை",
    moisture: "மண் ஈரம்",
    alerts: "எச்சரிக்கைகள்",
    scan_btn: "ஸ்கேன்",
    analyzing: "பகுப்பாய்வு...",
    confidence: "நம்பிக்கை",
    severity: "தீவிரம்",
    treatment: "சிகிச்சை",
    logout: "வெளியேறு",
    market: "சந்தை விலை",
    tasks: "பணிகள்",
    gen_report: "விரிவான அறிக்கை",
    enter_data: "தரவை உள்ளிடவும்",
    organic: "இயற்கை",
    chemical: "ரசாயன",
    disease_detected: "நோய் கண்டறியப்பட்டது",
    healthy: "பயிர் ஆரோக்கியமாக உள்ளது",
    greeting_morning: "காலை வணக்கம்",
    greeting_afternoon: "மதிய வணக்கம்",
    greeting_evening: "மாலை வணக்கம்",
    tutorial_intro: "நான் அக்ரிகார்ட், உங்கள் AI உதவியாளர். பண்ணையை கண்காணிக்க டாஷ்போர்டைப் பயன்படுத்தவும்.",
    magic_wand: "மேஜிக் வாண்ட்",
  },
  [Language.TELUGU]: {
    welcome: "స్వాగతం",
    tagline: "మీ AI వ్యవసాయ సహచరుడు",
    login: "లాగిన్",
    dashboard: "డాష్‌బోర్డ్",
    scanner: "పంట డాక్టర్",
    field: "క్షేత్ర ఆర్కిటెక్ట్",
    soil: "మట్టి ల్యాబ్",
    coach: "AI కోచ్",
    community: "కమ్యూనిటీ",
    weather: "వాతావరణం",
    moisture: "మట్టి తేమ",
    alerts: "హెచ్చరికలు",
    scan_btn: "స్కాన్",
    analyzing: "విశ్లేషిస్తోంది...",
    confidence: "నమ్మకం",
    severity: "తీవ్రత",
    treatment: "చికిత్స",
    logout: "లాగ్ అవుట్",
    market: "మార్కెట్ ధరలు",
    tasks: "పనులు",
    gen_report: "నివేదికను రూపొందించండి",
    enter_data: "డేటా నమోదు",
    organic: "సేంద్రీయ",
    chemical: "రసాయన",
    disease_detected: "వ్యాధి గుర్తించబడింది",
    healthy: "పంట ఆరోగ్యంగా ఉంది",
    greeting_morning: "శుభోదయం",
    greeting_afternoon: "శుభ మధ్యాహ్నం",
    greeting_evening: "శుభ సాయంత్రం",
    tutorial_intro: "నేను అగ్రిగార్డ్, మీ AI సహాయకుడిని. డాష్‌బోర్డ్‌ని ఉపయోగించండి.",
    magic_wand: "మ్యాజిక్ వాండ్",
  },
  [Language.MARATHI]: {
    welcome: "स्वागत आहे",
    tagline: "तुमचा एआय कृषी मित्र",
    login: "लॉगिन",
    dashboard: "डॅशबोर्ड",
    scanner: "पीक डॉक्टर",
    field: "शेती रचनाकार",
    soil: "माती आरोग्य",
    coach: "एआय कोच",
    community: "समुदाय",
    weather: "हवामान",
    moisture: "ओलावा",
    alerts: "सतर्कता",
    scan_btn: "स्कॅन",
    analyzing: "विश्लेषण...",
    confidence: "विश्वास",
    severity: "तीव्रता",
    treatment: "उपचार",
    logout: "बाहेर पडा",
    market: "बाजार भाव",
    tasks: "कामे",
    gen_report: "अहवाल तयार करा",
    enter_data: "माहिती भरा",
    organic: "सेंद्रिय",
    chemical: "रासायनिक",
    disease_detected: "रोग आढळला",
    healthy: "पीक निरोगी आहे",
    greeting_morning: "शुभ सकाळ",
    greeting_afternoon: "शुभ दुपार",
    greeting_evening: "शुभ संध्याकाळ",
    tutorial_intro: "मी ॲग्रीगार्ड आहे, तुमचा एआय सहाय्यक. शेतीचे निरीक्षण करण्यासाठी डॅशबोर्ड वापरा.",
    magic_wand: "जादुई कांडी",
  }
};

export const MOCK_USER: UserProfile = {
  name: "Rajesh Kumar",
  role: "Farmer",
  location: "Pune, Maharashtra",
  avatar: "https://i.pravatar.cc/150?u=rajesh",
  stats: { fields: 3, scans: 142, actionsPending: 2 }
};

export const INITIAL_SOIL_DATA = {
  ph: 6.8,
  moisture: 62,
  nitrogen: 140,
  phosphorus: 45,
  potassium: 180,
  ec: 1.2
};